sudo: required
services:
- docker
language: bash
install:
- mkdir dist
script:
- "./travis.sh"
before_deploy:
- sudo chmod 755 ./dist
- sudo chmod 644 ./dist/*
- sudo chown -R travis:travis ./dist
- ls -al ./dist/
deploy:
  provider: releases
  api_key:
    secure: wmCbUEYtT9yRj3YHSlTXUvkxPEsqwV5u4iLinfzejkZS+Y4/8CyHrdpVFJ41Cp+fXrKriaBMAIYF3CdTr5xTy5ut+jg5JZdsmtBy/kisL/aCFyHmVNil68SnBG5JQRroSR96OIX6qEaAq2wof0SHeOXOhzW9xIFUZPIjHoBw2Jj4CN3jFqawszIgtiGjG5KrtZ+FNYTsjFqUv/oJ+0+5w1hmv3QuDe67Qb8/0Vaa+fIcXrx7ZtRP0u2LtaQtQq2SQqimkHYYwhqZarylxHT/O1Ho9lTJMs38RrMtvuTB1dTg0DS+JpQbIZGTz437W6mUtGpxWLyX4PIjouQS/qu0RQEgKctwNB52L6dARYZpFlwUw1XXugQZere3WIpuhB0pfEZghSOA+41mPVyW0zIFvercwg4zIDsraLY3eQjhoOTnENJSsACmj3l2dRrxbUcYcqXzvgbbc6eheYOZtEzlACuuPEu2FLeZsHqfmQenGf/pw9gO/BTflEMgnfismordhtemY+ziZhvtnr9KHPUm3+i0XYzJ0DmiRXIq5woODIWvrvrISe73q/7PalPtwK0tZOHm9zPTIFMFOlZcP7hg1qlOxn9e6EFigqi2X4g97GAymLgtrteG3vJXkkNLBgisMvIzDPJg9+7EYcsmn/mnkJdrbHbk6z3QFC0g1lfFTt8=
  file: bla
  on:
    repo: nlm/multiarch-ipmitool-builder
    tags: on
  skip_cleanup: true
  file_glob: true
  file: "./dist/*"
