FROM multiarch/alpine:%%ARCH%%-%%ALPINE_VERSION%%

# Installing core packages
RUN apk update \
    && apk add \
        wget \
        automake \
        autoconf \
        build-base \
        file \
        libtool \
    && find /var/cache/apk -type f -delete

ADD assets/build-ipmitool /
RUN /build-ipmitool
RUN mkdir -p /workdir
CMD cp /usr/bin/ipmitool /workdir
